/**
 * Seed content for the one-time Firebase migration.
 *
 * This data was extracted verbatim from the former in-code defaults
 * (homeContent.js, pagesContent.js, admin settings) and the former
 * `initialXxx` arrays in the admin pages. It exists ONLY to populate
 * Firestore once; runtime code never imports this file.
 */

export const homeContent = {
    hero: {
        visible: true,
        kicker: 'WAYOUTS TRAVELS',
        titlePart1: 'Discover the world',
        titlePart2: 'with our guide.',
        description: 'Turn your dream destinations into reality with our expert guidance. From hidden gems to iconic landmarks, we create personalized journeys crafted just for you.',
        buttons: [
            { text: 'View tours', link: '/tours', style: 'butn-arrow2' },
        ],
        backgroundImage: '/assets/img/hero/pattern-bg.png',
        collage: {
            column1: ['/assets/img/a1.jpg', '/assets/img/a2.jpg', '/assets/img/a3.jpg', '/assets/img/a4.jpg'],
            column2: ['/assets/img/destination/a.jpg', '/assets/img/destination/c.jpg', '/assets/img/destination/e.jpg', '/assets/img/destination/f.jpg'],
            column3: ['/assets/img/blog/1.jpg', '/assets/img/blog/2.jpg', '/assets/img/blog/3.jpg', '/assets/img/blog/4.jpg'],
        },
        decorations: {
            star1: { visible: true, image: '/assets/img/hero/star2.png' },
            star2: { visible: true, image: '/assets/img/hero/flight-down.png' },
            star3: { visible: true, image: '/assets/img/hero/flight-up.png' },
            star4: { visible: true, image: '/assets/img/hero/bg-compass.png' },
        },
    },
    about: {
        visible: true,
        subtitle: 'About Wayouts India',
        titlePart1: 'Crafting Bespoke Journeys',
        titlePart2: 'Across India & Beyond',
        description: 'With dedicated travel desks assisting Kolkata and pan-India travelers, Wayouts transforms your dream holidays into seamless luxury experiences with private transfers, 5-star heritage stays, and expert local guides.',
        image1: '/assets/img/a4.jpg',
        image2: '/assets/img/a2.jpg',
        features: [
            { icon: 'fa-earth-americas', text: 'Pan-India Destinations' },
            { icon: 'fa-route', text: 'Tailored Itineraries' },
            { icon: 'fa-shield-heart', text: 'Safe & Insured Travels' },
            { icon: 'fa-hotel', text: 'Handpicked Luxury Stays' },
        ],
        avatars: ['/assets/img/team/tst1.jpg', '/assets/img/team/tst2.jpg', '/assets/img/team/tst3.jpg'],
        counterValue: '12,500+',
        counterLabel: 'Happy Indian Explorers',
        buttonText: 'Read our story',
        buttonLink: '/about',
        backgroundText: 'Wayouts',
    },
    featuredTours: {
        visible: true,
        subtitle: 'Choose your place',
        titlePart1: 'Discover dream',
        titleHighlight: 'Indian destinations',
        description: 'Experience the magic of India—from the snow-capped Himalayan peaks of Kashmir to the tranquil backwaters of Kerala and regal palaces of Rajasthan.',
        buttonText: 'View all tours',
        buttonLink: '/tours',
        tours: [
            {
                image: '/assets/img/destination/01.jpg',
                location: 'Kashmir, North India',
                title: 'Kashmir & Ladakh Paradise Escape',
                duration: '6 Days - 5 Nights',
                rating: '4.9',
                price: '₹24,999',
                priceUnit: '/ Traveler',
                link: '/tour-details',
            },
            {
                image: '/assets/img/destination/03.jpg',
                location: 'Kerala, South India',
                title: 'Kerala Backwaters & Munnar Tea Trails',
                duration: '5 Days - 4 Nights',
                rating: '4.9',
                price: '₹19,999',
                priceUnit: '/ Traveler',
                link: '/tour-details',
            },
            {
                image: '/assets/img/destination/02.jpg',
                location: 'Rajasthan, West India',
                title: 'Royal Rajasthan Heritage Circuit',
                duration: '7 Days - 6 Nights',
                rating: '4.8',
                price: '₹22,999',
                priceUnit: '/ Traveler',
                link: '/tour-details',
            },
        ],
    },
    services: {
        visible: true,
        titlePart1: 'Get ready to explore and',
        titlePart2: 'discover India.',
        circleText: 'Heritage Trails • Himalayan Escapes •',
        services: [
            { icon: 'fa-earth-americas', title: 'Hidden Indian Gems', link: '/service-details' },
            { icon: 'fa-plane', title: 'Domestic Flights & Transfers', link: '/service-details' },
            { icon: 'fa-mountain-sun', title: 'Himalayan Expeditions', link: '/service-details' },
            { icon: 'fa-camera-retro', title: 'Heritage & Culture Tours', link: '/service-details' },
        ],
        backgroundImage: '/assets/img/destination/01.jpg',
    },
    ticker: {
        visible: true,
        items: [
            'Kashmir & Ladakh Treks',
            'Kerala Houseboat Stays',
            'Rajasthan Fort Safaris',
            'Goa Coastal Retreats',
            'Sikkim & Darjeeling Tours',
            'Andaman Scuba Diving',
            'Golden Triangle Tours',
            'Varanasi Spiritual Walks',
            'Himachal Hill Stations',
            'Custom India Itineraries',
            'Chauffeur Driven Cars',
            'Luxury Palace Stays',
        ],
    },
    testimonials: {
        visible: true,
        subtitle: 'Traveler Stories',
        titlePart1: 'Our happy',
        titlePart2: 'explorers',
        testimonials: [
            {
                image: '/assets/img/testiominal/01.jpg',
                title: 'Kashmir Dal Lake & Gulmarg',
                rating: 5,
                text: 'We booked our family trip from Kolkata to Srinagar and Gulmarg with Wayouts. The private houseboat and snowy gondola ride were impeccably arranged!',
                reviewer: 'Sourav Banerjee',
                location: 'Salt Lake, Kolkata',
                avatars: ['/assets/img/team/tst1.jpg', '/assets/img/team/tst2.jpg', '/assets/img/team/tst3.jpg'],
            },
            {
                image: '/assets/img/testiominal/02.jpg',
                title: 'Kerala Backwaters Houseboat',
                rating: 5,
                text: 'Traveling from Kolkata for our honeymoon in Alleppey and Munnar was a dream. The private chef on our wooden houseboat served authentic local delicacies.',
                reviewer: 'Debjani & Anirban Ghosh',
                location: 'Ballygunge, Kolkata',
                avatars: ['/assets/img/team/tst1.jpg', '/assets/img/team/tst2.jpg', '/assets/img/team/tst3.jpg'],
            },
            {
                image: '/assets/img/testiominal/03.jpg',
                title: 'Sikkim & North Bengal Explorer',
                rating: 5,
                text: 'A seamless weekend getaway from Kolkata to Darjeeling and Pelling. Sunrise over Mt. Kangchenjunga with our expert local guide was truly breathtaking!',
                reviewer: 'Dr. Subhashis Mukherjee',
                location: 'New Town, Kolkata',
                avatars: ['/assets/img/team/tst1.jpg', '/assets/img/team/tst2.jpg', '/assets/img/team/tst3.jpg'],
            },
        ],
    },
    faqs: {
        visible: true,
        subtitle: 'Popular Questions',
        titlePart1: 'Frequently asked',
        titlePart2: 'questions',
        image1: '/assets/img/a2.jpg',
        image2: '/assets/img/a3.jpg',
        faqs: [
            {
                question: 'Custom Domestic & India Tour Packages',
                answer: 'We craft customized private itineraries across Kashmir, Kerala, Rajasthan, Himachal, Northeast India, and Andaman with chauffeur assistance.',
                icon: 'fa-route',
            },
            {
                question: 'Departures & Flights from Kolkata',
                answer: 'We provide direct flight bookings, airport transfers, and tailored departures from Kolkata (CCU) to major destinations across India.',
                icon: 'fa-plane',
            },
            {
                question: 'Luxury Lodging & Houseboats',
                answer: 'Enjoy curated 4-star and 5-star heritage palaces, premium Himalayan pine cottages, and private luxury houseboats.',
                icon: 'fa-hotel',
            },
        ],
        backgroundText: 'Questions',
    },
    blog: {
        visible: true,
        subtitle: 'Travel Blog',
        titlePart1: 'Incredible',
        titlePart2: 'India Stories',
        posts: [
            {
                image: '/assets/img/blog/1.jpg',
                date: '28 Aug 2026',
                title: 'Top 7 Hidden Valleys of Kashmir You Must Explore',
                excerpt: 'Beyond Dal Lake: Discover pristine pine meadows, gushing trout streams, and glacier passes in Aru and Betaab Valley.',
                postLink: '/post',
                blogLink: '/blog',
            },
            {
                image: '/assets/img/blog/2.jpg',
                date: '26 Aug 2026',
                title: 'A Culinary & Cultural Journey Through Old Kolkata to Darjeeling',
                excerpt: 'From colonial tea estates in the Himalayas to legendary street bites, experience the vibrant spirit of Eastern India.',
                postLink: '/post',
                blogLink: '/blog',
            },
            {
                image: '/assets/img/blog/3.jpg',
                date: '24 Aug 2026',
                title: 'The Ultimate Guide to Kerala Backwaters & Munnar Hills',
                excerpt: 'Plan the perfect monsoon and winter getaway amidst spice plantations, misty peaks, and serene lake cruises.',
                postLink: '/post',
                blogLink: '/blog',
            },
        ],
    },
    footer: {
        subtitle: 'SUBSCRIBE TO TRAVEL',
        titlePart1: 'Travel deals to your',
        titleHighlight: 'inbox!',
        privacyText: 'We are committed to protecting your',
        privacyLink: '#0',
        instagramHandle: 'WAYOUTS',
        instagramLink: 'https://instagram.com/wayouts_travels',
        instagramImages: [
            '/assets/img/insta/03.jpg',
            '/assets/img/insta/01.jpg',
            '/assets/img/insta/02.jpg',
            '/assets/img/insta/04.jpg',
            '/assets/img/insta/05.jpg',
            '/assets/img/insta/06.jpg'
        ],
    },
};

export const pagesContent = {
    about: {
        pageTitle: 'About Wayouts India',
        bannerSubtitle: 'ABOUT WAYOUTS',
        bannerTitle: 'Discover Incredible India with',
        bannerHighlight: 'Wayouts Luxury Travels',
        bannerImage: '/assets/img/7.jpg',
        aboutSubtitle: 'WHO WE ARE',
        aboutTitlePart1: 'Crafting Bespoke Journeys',
        aboutTitlePart2: 'Across India & Beyond',
        aboutDescription: 'Headquartered in India with dedicated operations assisting travelers from Kolkata and nationwide, Wayouts curates personalized holidays, private Himalayan expeditions, royal palace retreats, and serene backwater cruises.',
        aboutImage1: '/assets/img/a4.jpg',
        aboutImage2: '/assets/img/a2.jpg',
        counterValue: '12,500+',
        counterLabel: 'Happy Indian Travelers',
        experienceTitle1: 'Get ready to explore and',
        experienceTitle2: 'discover India’s rich heritage.',
        experienceBgImage: '/assets/img/destination/01.jpg',
        teamSubtitle: 'OUR EXPERTS',
        teamTitle1: 'Meet our India',
        teamTitle2: 'Travel Designers',
    },
    tours: {
        pageTitle: 'Tours & Packages India',
        bannerSubtitle: 'EXPLORE OUR TOURS',
        bannerTitle: 'Discover',
        bannerHighlight: 'unforgettable journeys across India',
        bannerImage: '/assets/img/destination/01.jpg',
        sectionSubtitle: 'POPULAR DOMESTIC ITINERARIES',
        sectionTitle1: 'Handcrafted luxury tours &',
        sectionTitle2: 'holiday packages in India.',
    },
    destinations: {
        pageTitle: 'Indian Destinations',
        bannerSubtitle: 'EXPLORE OUR DESTINATIONS',
        bannerTitle: "Explore India's most",
        bannerHighlight: 'enchanting destinations',
        bannerImage: '/assets/img/destination/02.jpg',
        sectionSubtitle: 'POPULAR INDIAN REGIONS',
        sectionTitle1: 'Handcrafted itineraries across',
        sectionTitle2: 'the Himalayas, Backwaters & Coasts.',
    },
    services: {
        pageTitle: 'Premium Travel Services India',
        bannerSubtitle: 'OUR TRAVEL SERVICES',
        bannerTitle: 'Discover services that make',
        bannerHighlight: 'Indian travel effortless',
        bannerImage: '/assets/img/destination/05.jpg',
        quoteText: 'WAYOUTS transforms journeys into unforgettable Indian experiences.',
    },
    blog: {
        pageTitle: 'Incredible India Travel Journal',
        bannerSubtitle: 'LATEST TRAVEL STORIES',
        bannerTitle: 'Inspiring stories for your next',
        bannerHighlight: 'Indian adventure',
        bannerImage: '/assets/img/destination/03.jpg',
    },
    post: {
        pageTitle: 'Kashmir Valley Travel Guide',
        bannerSubtitle: 'LATEST TRAVEL STORIES',
        bannerTitle: 'Top 7 Hidden Valleys of Kashmir You',
        bannerHighlight: 'Must Explore',
        authorName: 'Sourav Banerjee',
        authorRole: 'Traveler from Kolkata',
        authorAvatar: '/assets/img/team/tst1.jpg',
        postDate: '28 Aug 2026',
        bannerImage: '/assets/img/destination/03.jpg',
        leadQuote: 'Kashmir is not just a destination; it is an unforgettable emotion of pine valleys and snowy peaks.',
        leadQuoteCite: 'Anonymous Explorer',
        leadText1: 'Beyond Dal Lake and standard tourist trails, Kashmir offers pristine pine meadows, gushing trout streams, and glacier passes in Aru, Betaab Valley, and Gurez.',
        bodyParagraph1: 'From staying in authentic wooden houseboats on Nigeen Lake to taking the high-altitude Gulmarg Gondola above the clouds, Kashmir remains India’s crowning jewel for mountain enthusiasts and romantic getaways.',
        bodyParagraph2: 'Savor traditional Kashmiri Wazwan cuisine, sip steaming Kehwa by the fireplace, and explore apple orchards under the gentle autumn sun.',
        commentUser: 'Dr. Subhashis Mukherjee',
        commentRole: 'Traveler from Kolkata',
        commentAvatar: '/assets/img/team/g1.jpg',
        commentText: 'Our trip to Kashmir with Wayouts was arranged to perfection. The local chauffeur and private houseboat stay exceeded all our expectations.',
    },
    contact: {
        pageTitle: 'Contact Wayouts Travels',
        bannerSubtitle: 'TALK TO OUR INDIA TRAVEL EXPERTS',
        bannerTitle: 'Get personalized holiday planning',
        bannerHighlight: 'support today!',
        bannerImage: '/assets/img/destination/03.jpg',
        formHeadline: 'Plan Your Next Indian Getaway!',
        phone: '+91 98765 43210',
        email: 'contact@wayouts.com',
        address: '402, Signature One, S.G. Highway, Ahmedabad & Salt Lake, Kolkata, India',
    },
    faq: {
        pageTitle: 'Frequently Asked Questions',
        bannerSubtitle: 'Popular Questions',
        bannerTitle: 'Everything you need to know about',
        bannerHighlight: 'booking with Wayouts India',
        bannerImage: '/assets/img/destination/05.jpg',
    },
    team: {
        pageTitle: 'Our Travel Experts & Guides',
        bannerSubtitle: 'Meet The Team',
        bannerTitle: 'Passionate travel designers &',
        bannerHighlight: 'local Indian guides',
        bannerImage: '/assets/img/destination/02.jpg',
    },
    testimonials: {
        pageTitle: 'Client Testimonials',
        bannerSubtitle: 'Traveler Stories',
        bannerTitle: 'What our happy guests say',
        bannerHighlight: 'about their journeys across India',
        bannerImage: '/assets/img/destination/01.jpg',
    },
};

export const siteSettings = {
    agencyName: 'Wayouts Luxury Travels',
    tagline: 'Crafting Unforgettable Journeys Across India & Beyond',
    logoDark: '/assets/img/logo-dark.png',
    logoLight: '/assets/img/logo.png',
    favicon: '/assets/img/favicon.ico',
    primaryCurrency: 'INR (₹)',
    timezone: 'IST (UTC+05:30)',
    supportEmail: 'contact@wayouts.com',
    bookingHotline: '+91 98765 43210',
    whatsappNumber: '+91 98765 43210',
    headquartersAddress: '402, Signature One, S.G. Highway, Ahmedabad, Gujarat 380054, India',
    officeHours: 'Monday – Saturday: 9:30 AM – 7:30 PM',
    instagramUrl: 'https://instagram.com/wayouts_travels',
    facebookUrl: 'https://facebook.com/wayoutstravels',
    youtubeUrl: 'https://youtube.com/@wayoutstravels',
    enableOnlineBookings: true,
    enableInstantWhatsAppInquiry: true,
    enableNewsletterPopup: true,
    enableSeasonalOffersBanner: false,
    seasonalBannerText: 'Diwali Early-Bird: Flat 15% Off On All Kashmir & Kerala Winter Packages! Use Code: DIWALI15',
    defaultMetaTitle: 'Wayouts — Luxury Travel & Adventure Tour Operator India',
    defaultMetaDescription: 'Discover handcrafted luxury holiday packages, private chauffeur tours, mountain expeditions, and tropical retreats with Wayouts Travels.',
    defaultKeywords: 'luxury tours india, kashmir holiday packages, kerala backwaters, rajasthan royal tour, travel agency india',
};

export const collections = {
    tours: [
        {
            id: 'tour-1',
            name: 'Maldives Paradise Escape',
            bannerSubtitle: 'Explore Our Tours',
            destination: 'Maldives, Asia',
            duration: '6 Days - 5 Nights',
            tourDate: '26.05.2027',
            price: '₹39,999',
            rating: '4.9',
            reviewsCount: '128',
            groupSize: '15 - 20 People',
            featured: true,
            image: '/assets/img/destination/01.jpg',
            gallery: [
                '/assets/img/destination/a.jpg',
                '/assets/img/destination/b.jpg',
                '/assets/img/destination/c.jpg',
                '/assets/img/destination/d.jpg'
            ],
            overview: 'Escape to pure paradise with our Maldives Paradise Escape tour. Experience crystal-clear turquoise waters, white sandy beaches, and luxurious island resorts. This carefully designed package offers the perfect balance of relaxation, adventure, and unforgettable tropical beauty.',
            highlights: [
                'Stay in a five star beachfront resort',
                'Direct access to private beaches',
                'Sunset cruises and dolphin watching'
            ],
            bestTimeToVisit: 'November – April (dry season, best weather conditions)',
            whoIsItFor: 'Couples, honeymooners, families, and luxury travel lovers',
            included: ['Daily breakfast', 'Guided island activities', 'Welcome assistance on arrival'],
            excluded: ['International flights', 'Personal expenses', 'Optional tours & activities'],
            status: 'Active',
        },
        {
            id: 'tour-2',
            name: 'Dubai Luxury Journey',
            bannerSubtitle: 'Explore Our Tours',
            destination: 'Dubai, UAE',
            duration: '5 Days - 4 Nights',
            tourDate: '15.09.2026',
            price: '₹55,999',
            rating: '4.8',
            reviewsCount: '94',
            groupSize: '12 - 16 People',
            featured: true,
            image: '/assets/img/destination/03.jpg',
            gallery: [
                '/assets/img/destination/03.jpg',
                '/assets/img/destination/a.jpg',
                '/assets/img/destination/b.jpg'
            ],
            overview: 'Discover futuristic architecture, luxury desert safaris, and vibrant gold souks in modern Dubai.',
            highlights: ['Burj Khalifa Observation Deck', 'Desert Safari with BBQ Dinner', 'Dubai Marina Yacht Tour'],
            bestTimeToVisit: 'October – April (pleasant desert climate)',
            whoIsItFor: 'Luxury seekers, shoppers, families, and architectural enthusiasts',
            included: ['4-Star Luxury Hotel', 'Desert Safari with Transfers', 'City Sightseeing Tour'],
            excluded: ['Visa Fee', 'International Airfare'],
            status: 'Active',
        },
        {
            id: 'tour-3',
            name: 'Canadian Nature Tour',
            bannerSubtitle: 'Explore Our Tours',
            destination: 'Banff, Canada',
            duration: '7 Days - 6 Nights',
            tourDate: '10.07.2026',
            price: '₹63,999',
            rating: '4.9',
            reviewsCount: '86',
            groupSize: '10 - 15 People',
            featured: true,
            image: '/assets/img/destination/02.jpg',
            gallery: [
                '/assets/img/destination/02.jpg',
                '/assets/img/destination/c.jpg'
            ],
            overview: 'Immerse yourself in the breathtaking Canadian Rockies, turquoise glacier lakes, and alpine wildlife trails.',
            highlights: ['Lake Louise & Moraine Lake Tour', 'Icefields Parkway Scenic Drive', 'Banff Gondola Ride'],
            bestTimeToVisit: 'June – September (hiking and emerald lakes season)',
            whoIsItFor: 'Hikers, photographers, nature lovers, and adventure seekers',
            included: ['Lodge Accommodation', 'Park Entry Permits', 'Professional Mountain Guide'],
            excluded: ['Flight Tickets', 'Personal Gear'],
            status: 'Active',
        },
        {
            id: 'tour-4',
            name: 'Greek Paradise Tour',
            bannerSubtitle: 'Explore Our Tours',
            destination: 'Santorini, Greece',
            duration: '7 Days - 6 Nights',
            tourDate: '18.06.2026',
            price: '₹71,999',
            rating: '4.8',
            reviewsCount: '112',
            groupSize: '12 - 18 People',
            featured: false,
            image: '/assets/img/destination/05.jpg',
            gallery: [
                '/assets/img/destination/05.jpg',
                '/assets/img/destination/d.jpg'
            ],
            overview: 'Wander whitewashed cliffside villages, azure waters, volcanic beaches, and world-famous Aegean sunsets.',
            highlights: ['Oia Sunset Walking Tour', 'Catamaran Caldera Cruise', 'Local Wine Tasting Tour'],
            bestTimeToVisit: 'May – October (warm Aegean sunshine)',
            whoIsItFor: 'Couples, honeymooners, culture lovers, and foodies',
            included: ['Boutique Hotel Stay', 'Daily Continental Breakfast', 'Catamaran Cruise with Lunch'],
            excluded: ['Airfare', 'Personal Shopping'],
            status: 'Draft',
        },
    ],
    destinations: [
        {
            id: 'dest-1',
            name: 'Kashmir & Ladakh',
            region: 'North India',
            packages: '5+ Tour Packages',
            travelers: '2,450+',
            startingPrice: '₹24,999',
            bestSeason: 'April – October (Kashmir) / June – Sept (Ladakh)',
            featured: true,
            image: '/assets/img/destination/01.jpg',
            description: 'Pristine Dal Lake shikaras, snowcapped Himalayan peaks, Pangong Tso, and high-altitude mountain passes.',
            status: 'Published',
        },
        {
            id: 'dest-2',
            name: 'Kerala & Backwaters',
            region: 'South India',
            packages: '6+ Tour Packages',
            travelers: '3,180+',
            startingPrice: '₹19,999',
            bestSeason: 'September – March',
            featured: true,
            image: '/assets/img/destination/a.jpg',
            description: 'Serene Alleppey houseboats, Munnar tea estates, Ayurvedic wellness retreats, and coastal palm beaches.',
            status: 'Published',
        },
        {
            id: 'dest-3',
            name: 'Rajasthan & Golden Triangle',
            region: 'North India',
            packages: '7+ Tour Packages',
            travelers: '4,200+',
            startingPrice: '₹22,999',
            bestSeason: 'October – March',
            featured: true,
            image: '/assets/img/destination/d.jpg',
            description: 'Majestic Jaipur forts, Udaipur royal palaces, Thar desert camel safaris, and rich heritage folklore.',
            status: 'Published',
        },
        {
            id: 'dest-4',
            name: 'Goa Coastline',
            region: 'West India',
            packages: '4+ Tour Packages',
            travelers: '5,600+',
            startingPrice: '₹14,999',
            bestSeason: 'October – May',
            featured: true,
            image: '/assets/img/destination/c.jpg',
            description: 'Sun-kissed Arabian sea beaches, Portuguese heritage churches, luxury beach resorts, and nightlife.',
            status: 'Published',
        },
        {
            id: 'dest-5',
            name: 'Sikkim & Darjeeling',
            region: 'East & Northeast India',
            packages: '4+ Tour Packages',
            travelers: '1,840+',
            startingPrice: '₹21,999',
            bestSeason: 'March – June / September – December',
            featured: true,
            image: '/assets/img/destination/02.jpg',
            description: 'Kangchenjunga sunrise vistas, Buddhist monasteries, toy train rides, and alpine rhododendron valleys.',
            status: 'Published',
        },
        {
            id: 'dest-6',
            name: 'Andaman & Nicobar Islands',
            region: 'Islands & Coastal India',
            packages: '4+ Tour Packages',
            travelers: '1,950+',
            startingPrice: '₹28,999',
            bestSeason: 'October – May',
            featured: true,
            image: '/assets/img/destination/f.jpg',
            description: 'Radhanagar blue waters, scuba diving at Havelock Island, coral reefs, and tranquil cellular heritage.',
            status: 'Published',
        },
    ],
    services: [
        {
            id: 'serv-1',
            title: 'Custom Tour Packages',
            subtitle: 'Personalized Itineraries & Holidays',
            icon: 'fa-thin fa-route',
            image: '/assets/img/destination/01.jpg',
            desc: 'Personalized travel plans tailored to your interests, schedule, and budget across India and beyond.',
            overview: 'Discover bespoke holiday packages crafted with luxury stays, private chauffeur transfers, and exclusive sightseeing experiences.',
            features: [
                'Tailor-made itineraries with private guide options',
                'Handpicked luxury hotels and premium boutique resorts',
                'Flexible departure dates and custom flight bookings',
                'Dedicated concierge support throughout your vacation'
            ],
            badge: 'Top Popular',
            order: 1,
            status: 'Active',
        },
        {
            id: 'serv-2',
            title: 'Flight & Airline Booking',
            subtitle: 'Domestic & Global Flight Reservations',
            icon: 'fa-thin fa-plane-departure',
            image: '/assets/img/destination/03.jpg',
            desc: 'Fast, secure flight reservations at the best available corporate and holiday fares.',
            overview: 'Access direct airline ticketing, flexible rescheduling options, seat preference selection, and real-time flight notifications.',
            features: [
                'Best negotiated rates on major domestic and global carriers',
                'Hassle-free baggage assistance and priority check-in tips',
                'Instant e-ticket generation and live status tracking',
                '24/7 rescheduling and cancellation emergency desk'
            ],
            badge: 'Best Rates',
            order: 2,
            status: 'Active',
        },
        {
            id: 'serv-3',
            title: 'Hotel & Luxury Accommodation',
            subtitle: '5-Star Stays, Villas & Resorts',
            icon: 'fa-thin fa-hotel',
            image: '/assets/img/destination/02.jpg',
            desc: 'Comfortable, verified luxury accommodation options with complimentary breakfast and perks.',
            overview: 'From scenic mountain chalets in Kashmir to overwater villas in the Maldives and royal heritage havelis in Rajasthan.',
            features: [
                'Direct partnerships with top international hotel brands',
                'Complimentary room upgrades and wellness inclusions',
                'Verified guest reviews, hygiene standards, and safety',
                'Early check-in and late checkout privileges'
            ],
            badge: 'Verified',
            order: 3,
            status: 'Active',
        },
        {
            id: 'serv-4',
            title: 'Visa & Travel Documentation',
            subtitle: 'Fast-Track Processing & Consular Support',
            icon: 'fa-thin fa-passport',
            image: '/assets/img/destination/04.jpg',
            desc: 'Professional document verification and visa application assistance for all major destinations.',
            overview: 'End-to-end guidance through embassy paperwork, appointment scheduling, biometrics preparation, and passport dispatch.',
            features: [
                'Comprehensive document screening and verification checklist',
                'Expedited tourist and business visa assistance',
                'Embassies appointment booking and interview tips',
                'Complimentary mandatory travel insurance guidance'
            ],
            badge: 'Fast Track',
            order: 4,
            status: 'Active',
        },
        {
            id: 'serv-5',
            title: 'Airport & Intercity Transfers',
            subtitle: 'Chauffeur Driven Private Fleets',
            icon: 'fa-thin fa-van-shuttle',
            image: '/assets/img/destination/05.jpg',
            desc: 'Reliable private airport pickups, luxury sedans, and air-conditioned coaches for stress-free journeys.',
            overview: 'Experienced multilingual drivers, GPS-monitored premium vehicles, and punctual transfers between airports, hotels, and tourist spots.',
            features: [
                'Clean sanitized fleet with sanitized AC interiors',
                'Punctual flight delay monitoring and meet-and-greet',
                'English & Hindi speaking professional chauffeurs',
                'Fixed upfront pricing with zero hidden surcharge fees'
            ],
            badge: 'Private Fleet',
            order: 5,
            status: 'Active',
        },
        {
            id: 'serv-6',
            title: '24/7 Traveler Emergency Support',
            subtitle: 'Dedicated Travel Concierge Team',
            icon: 'fa-thin fa-headset',
            image: '/assets/img/destination/06.jpg',
            desc: 'Dedicated multilingual support available anytime during your journey via WhatsApp and phone.',
            overview: 'Round-the-clock assistance for flight delays, emergency medical coordination, hotel requests, and on-trip itinerary adjustments.',
            features: [
                'Dedicated personal tour manager assigned to your trip',
                'Instant WhatsApp live chat and emergency hotlines',
                'Real-time weather, local travel alerts, and advisory',
                'Lost luggage recovery coordination'
            ],
            badge: '24x7 Live',
            order: 6,
            status: 'Active',
        },
    ],
    team: [
        {
            id: 'tm-1',
            name: 'Emily White',
            role: 'Travel Director & Founder',
            specialization: 'Luxury Escapes & Northern Himalayas',
            email: 'emily@wayouts.com',
            phone: '+91 98765 43210',
            tours: 18,
            experience: '12+ Years',
            image: '/assets/img/team/tst1.jpg',
            bio: 'Over a decade designing high-end bespoke holiday experiences across Kashmir, Ladakh, and international luxury retreats.',
            socialInstagram: 'https://instagram.com',
            socialLinkedin: 'https://linkedin.com',
            featured: true,
            status: 'Active',
        },
        {
            id: 'tm-2',
            name: 'Daniel Scott',
            role: 'Senior Expeditions Guide',
            specialization: 'Wildlife Safaris & Trekking',
            email: 'daniel@wayouts.com',
            phone: '+91 98765 43211',
            tours: 24,
            experience: '9+ Years',
            image: '/assets/img/team/1.jpg',
            bio: 'Certified wilderness first-responder leading high-altitude Himalayan treks and national park tiger safaris.',
            socialInstagram: 'https://instagram.com',
            socialLinkedin: 'https://linkedin.com',
            featured: true,
            status: 'Active',
        },
        {
            id: 'tm-3',
            name: 'Sarah Kim',
            role: 'Destination Specialist',
            specialization: 'Cultural Heritage & Royal Circuits',
            email: 'sarah@wayouts.com',
            phone: '+91 98765 43212',
            tours: 15,
            experience: '7+ Years',
            image: '/assets/img/team/3.jpg',
            bio: 'Specializing in historical architecture, culinary trails, and authentic cultural encounters in Rajasthan and South India.',
            socialInstagram: 'https://instagram.com',
            socialLinkedin: 'https://linkedin.com',
            featured: true,
            status: 'Active',
        },
        {
            id: 'tm-4',
            name: 'Michael Reed',
            role: 'Guest Experience & Concierge',
            specialization: 'VIP Logistics & Wellness',
            email: 'michael@wayouts.com',
            phone: '+91 98765 43213',
            tours: 11,
            experience: '6+ Years',
            image: '/assets/img/team/4.jpg',
            bio: 'Dedicated to ensuring seamless 24/7 airport handling, luxury villa stays, and bespoke on-ground hospitality.',
            socialInstagram: 'https://instagram.com',
            socialLinkedin: 'https://linkedin.com',
            featured: false,
            status: 'Active',
        },
    ],
    posts: [
        {
            id: 'post-1',
            title: 'Exploring the hidden paradise of Kashmir & Ladakh',
            category: 'Travel Tips',
            author: 'Emily Brown',
            authorAvatar: '/assets/img/team/tst1.jpg',
            date: '28 Dec 2026',
            readTime: '5 min read',
            image: '/assets/img/blog/1.jpg',
            excerpt: 'Discover a world where turquoise lakes meet towering Himalayan snowcaps and ancient monasteries.',
            leadQuote: 'The mountains are calling and I must go to the valleys of northern bliss.',
            leadQuoteCite: 'John Muir',
            leadText: 'Experience the pristine beauty and vibrant local culture of the high Himalayas...',
            bodyParagraph1: 'From scenic shikara rides across Dal Lake to adventurous drives through Khardung La pass...',
            bodyParagraph2: 'Immerse yourself in mountain serenity and taste authentic Kashmiri wazwan cuisine...',
            featured: true,
            status: 'Published',
        },
        {
            id: 'post-2',
            title: 'Journey through Kerala backwaters and spice plantations',
            category: 'Destinations',
            author: 'Daniel Scott',
            authorAvatar: '/assets/img/team/1.jpg',
            date: '26 Dec 2026',
            readTime: '6 min read',
            image: '/assets/img/blog/2.jpg',
            excerpt: 'Glide through palm-fringed lagoons, aromatic tea slopes of Munnar, and tranquil coastal resorts.',
            leadQuote: 'Gods own country offers tranquility that heals the modern soul.',
            leadQuoteCite: 'Traveler Journal',
            leadText: 'Kerala presents an unmatched ecosystem of emerald backwaters and traditional wellness...',
            bodyParagraph1: 'Spending a night aboard an authentic wooden houseboat surrounded by gentle waters...',
            bodyParagraph2: 'Explore historic Fort Kochi, colonial Dutch heritage, and classic Kathakali performances...',
            featured: true,
            status: 'Published',
        },
        {
            id: 'post-3',
            title: 'Royal palaces, forts, and desert safaris of Rajasthan',
            category: 'Culture & Heritage',
            author: 'Sarah Kim',
            authorAvatar: '/assets/img/team/3.jpg',
            date: '24 Dec 2026',
            readTime: '4 min read',
            image: '/assets/img/blog/3.jpg',
            excerpt: 'Step into the land of maharajas, vibrant folk music, golden sand dunes, and grandeur architecture.',
            leadQuote: 'Every palace in Rajasthan tells a legend of valor, love, and imperial royalty.',
            leadQuoteCite: 'Heritage Guide',
            leadText: 'Rajasthan is an open-air museum filled with timeless forts and colorful bazaars...',
            bodyParagraph1: 'Wander through the pink city of Jaipur and the romantic lake palace of Udaipur...',
            bodyParagraph2: 'Camp beneath the starry desert sky in Jaisalmer with traditional folk dances...',
            featured: true,
            status: 'Published',
        },
        {
            id: 'post-4',
            title: 'Essential packing checklist for Indian tropical adventures',
            category: 'Inspiration',
            author: 'Michael Reed',
            authorAvatar: '/assets/img/team/4.jpg',
            date: '20 Dec 2026',
            readTime: '3 min read',
            image: '/assets/img/blog/4.jpg',
            excerpt: 'Expert tips on clothing, footwear, camera gear, and seasonal preparation for diverse terrains.',
            leadQuote: 'Travel light, travel smart, and leave room in your bag for memories.',
            leadQuoteCite: 'Packing Pro',
            leadText: 'Packing for a varied subcontinent journey requires mindful selection and breathable fabrics...',
            bodyParagraph1: 'Ensure lightweight cottons for coastal zones and warm thermal layers for northern heights...',
            bodyParagraph2: 'Always carry eco-friendly sunscreen, hydration bottles, and quick-dry shoes...',
            featured: false,
            status: 'Draft',
        },
    ],
    testimonials: [
        {
            id: 'rev-1',
            name: 'Aarav Sharma',
            location: 'Mumbai, India',
            avatar: '/assets/img/team/tst1.jpg',
            tourName: 'Kashmir & Ladakh Escape',
            rating: 5,
            date: '24 Aug 2026',
            title: 'Unforgettable Himalayan Experience',
            comment: 'The houseboat stay on Dal Lake and the drive to Pangong Tso were organized to perfection. Truly a 5-star trip!',
            featured: true,
            status: 'Approved',
        },
        {
            id: 'rev-2',
            name: 'Pooja Iyer',
            location: 'Bengaluru, India',
            avatar: '/assets/img/team/1.jpg',
            tourName: 'Kerala Backwaters & Tea Trails',
            rating: 5,
            date: '18 Aug 2026',
            title: 'Peaceful and luxurious',
            comment: 'Munnar tea estates and the Alleppey private cruise exceeded all our expectations. Seamless chauffeur service throughout.',
            featured: true,
            status: 'Approved',
        },
        {
            id: 'rev-3',
            name: 'Rohan Mehta',
            location: 'Delhi NCR',
            avatar: '/assets/img/team/3.jpg',
            tourName: 'Royal Rajasthan Heritage Circuit',
            rating: 5,
            date: '12 Aug 2026',
            title: 'Palaces, safaris and royal hospitality',
            comment: 'From Jaipur palaces to desert camping in Jaisalmer under the stars, every single detail was taken care of.',
            featured: true,
            status: 'Approved',
        },
        {
            id: 'rev-4',
            name: 'Ananya Deshmukh',
            location: 'Pune, India',
            avatar: '/assets/img/team/4.jpg',
            tourName: 'Goa Coastal Serenity',
            rating: 4,
            date: '05 Aug 2026',
            title: 'Great beach resort selection',
            comment: 'Very relaxing holiday. The private transfers were punctual and the resort recommendations were spot on.',
            featured: false,
            status: 'Pending',
        },
    ],
    faqs: [
        {
            id: 'faq-1',
            question: 'How do I customize an Indian tour package with Wayouts?',
            category: 'Booking & Customization',
            icon: 'fa-thin fa-route',
            answer: 'You can choose any existing package or share your travel dates, preferred destinations, hotel categories, and activities with our travel designers. We craft a bespoke itinerary with private transfers and guide options within 24 hours.',
            order: 1,
            status: 'Published',
        },
        {
            id: 'faq-2',
            question: 'What are the payment methods and currency options?',
            category: 'Payments & Pricing',
            icon: 'fa-thin fa-credit-card',
            answer: 'All our prices are denominated in Indian Rupees (₹). We accept UPI, Net Banking, major Credit/Debit Cards, and NEFT/RTGS bank transfers. Flexible installment payment options are available for advance bookings.',
            order: 2,
            status: 'Published',
        },
        {
            id: 'faq-3',
            question: 'Are flights and visa assistance included in packages?',
            category: 'Flights & Visa',
            icon: 'fa-thin fa-plane-departure',
            answer: 'Domestic transfers and selected flights can be bundled seamlessly into your package. For international destinations, our dedicated visa desk assists you with appointment booking, document screening, and fast-track processing.',
            order: 3,
            status: 'Published',
        },
        {
            id: 'faq-4',
            question: 'What is your cancellation and refund policy?',
            category: 'Cancellations & Refunds',
            icon: 'fa-thin fa-shield-check',
            answer: 'Cancellations requested 30 days prior to departure receive up to 90% refund minus minimal administrative charges. For bookings closer to departure, refund percentages depend on airline and hotel partner policies.',
            order: 4,
            status: 'Published',
        },
        {
            id: 'faq-5',
            question: 'Do you provide 24/7 on-trip assistance during the tour?',
            category: 'Customer Support',
            icon: 'fa-thin fa-headset',
            answer: 'Yes. Every booking includes a dedicated personal tour concierge reachable 24/7 via WhatsApp and direct hotline for flight updates, emergency support, hotel requests, and local assistance.',
            order: 5,
            status: 'Published',
        },
    ],
    bookings: [
        {
            id: 'WY-1048',
            guest: 'Aarav Sharma',
            email: 'aarav.sharma@example.com',
            phone: '+91 98201 23456',
            tour: 'Kashmir & Ladakh Escape',
            travelers: 2,
            departureDate: '15 Sep 2026',
            amount: '₹49,998',
            paymentStatus: 'Paid',
            bookingDate: '24 Aug 2026',
            specialRequests: 'Window seat preference on domestic transfers and vegetarian meals.',
            status: 'Confirmed',
        },
        {
            id: 'WY-1047',
            guest: 'Pooja Iyer',
            email: 'pooja.iyer@example.com',
            phone: '+91 98450 78901',
            tour: 'Kerala Backwaters & Tea Trails',
            travelers: 4,
            departureDate: '22 Sep 2026',
            amount: '₹79,996',
            paymentStatus: 'Partially Paid',
            bookingDate: '22 Aug 2026',
            specialRequests: 'Private wooden houseboat with interconnected bedroom.',
            status: 'Pending',
        },
        {
            id: 'WY-1046',
            guest: 'Rohan Mehta',
            email: 'rohan.mehta@example.com',
            phone: '+91 98110 54321',
            tour: 'Royal Rajasthan Heritage Circuit',
            travelers: 2,
            departureDate: '05 Oct 2026',
            amount: '₹45,998',
            paymentStatus: 'Paid',
            bookingDate: '19 Aug 2026',
            specialRequests: 'Desert tent luxury upgrade and camel sunset safari.',
            status: 'Confirmed',
        },
        {
            id: 'WY-1045',
            guest: 'Ananya Deshmukh',
            email: 'ananya.d@example.com',
            phone: '+91 97654 32109',
            tour: 'Goa Coastal Serenity',
            travelers: 3,
            departureDate: '12 Oct 2026',
            amount: '₹44,997',
            paymentStatus: 'Refunded',
            bookingDate: '15 Aug 2026',
            specialRequests: 'Trip postponed due to schedule conflict.',
            status: 'Cancelled',
        },
        {
            id: 'WY-1044',
            guest: 'Vikramjit Singh',
            email: 'vikram.singh@example.com',
            phone: '+91 98722 11223',
            tour: 'Sikkim & Darjeeling Explorer',
            travelers: 2,
            departureDate: '18 Oct 2026',
            amount: '₹43,998',
            paymentStatus: 'Paid',
            bookingDate: '12 Aug 2026',
            specialRequests: 'Early morning Kangchenjunga sunrise view guide.',
            status: 'Confirmed',
        },
    ],
    customers: [
        {
            id: 'cust-1',
            name: 'Sourav Banerjee',
            email: 'sourav.banerjee@kolkata.in',
            phone: '+91 98301 44552',
            city: 'Salt Lake, Kolkata',
            trips: 4,
            spent: '₹1,98,400',
            joined: '18 Jan 2026',
            tier: 'Platinum Member',
            status: 'Active',
            notes: 'Frequent traveler to Kashmir and Himachal. Prefers direct flights from Kolkata (CCU) and 5-star heritage hotels.',
        },
        {
            id: 'cust-2',
            name: 'Debjani & Anirban Ghosh',
            email: 'anirban.ghosh@calcutta.org',
            phone: '+91 98310 88990',
            city: 'Ballygunge, Kolkata',
            trips: 3,
            spent: '₹1,44,990',
            joined: '07 Feb 2026',
            tier: 'Gold Member',
            status: 'Active',
            notes: 'Honeymoon and anniversary family trips to Kerala and Andaman. Loves private wooden houseboats.',
        },
        {
            id: 'cust-3',
            name: 'Dr. Subhashis Mukherjee',
            email: 'dr.subhashis@medkolkata.com',
            phone: '+91 98300 77112',
            city: 'New Town, Kolkata',
            trips: 6,
            spent: '₹2,87,200',
            joined: '22 Mar 2026',
            tier: 'VIP Elite',
            status: 'Active',
            notes: 'Senior consulting physician. Books Himalayan mountain treks, Sikkim, and Ladakh private expeditions.',
        },
        {
            id: 'cust-4',
            name: 'Priyanka Sen',
            email: 'priyanka.sen@designkolkata.com',
            phone: '+91 98365 22334',
            city: 'Park Street, Kolkata',
            trips: 2,
            spent: '₹89,400',
            joined: '11 Apr 2026',
            tier: 'Silver Member',
            status: 'Active',
            notes: 'Architect & photographer. Enjoys royal fort photography in Rajasthan and coastal Goa.',
        },
        {
            id: 'cust-5',
            name: 'Indranil Roychowdhury',
            email: 'indranil.rc@bengalcorp.in',
            phone: '+91 98312 99001',
            city: 'Alipore, Kolkata',
            trips: 5,
            spent: '₹3,20,000',
            joined: '04 May 2026',
            tier: 'VIP Elite',
            status: 'Active',
            notes: 'Corporate executive. Requires luxury chauffeur-driven vehicles, palace stays, and airport lounge access.',
        },
    ],
    inquiries: [
        {
            id: 'inq-1',
            from: 'Rajesh Nair',
            email: 'rajesh.nair@example.com',
            phone: '+91 98401 55667',
            subject: 'Custom family package for Kashmir in October',
            channel: 'Website Form',
            date: '27 Aug 2026',
            travelers: '4 Adults, 1 Child',
            budget: '₹1,50,000 - ₹2,000,000',
            message: 'Looking for a 6N/7D trip covering Srinagar, Gulmarg, and Pahalgam with 4-star hotels and private Innova Crysta.',
            status: 'New',
        },
        {
            id: 'inq-2',
            from: 'Sunita Menon',
            email: 'sunita.m@example.com',
            phone: '+91 98230 44556',
            subject: 'Kerala honeymoon package with luxury houseboat',
            channel: 'WhatsApp Inquiry',
            date: '26 Aug 2026',
            travelers: '2 Adults',
            budget: '₹80,000 - ₹1,20,000',
            message: 'Need a honeymoon package with private pool villa in Munnar and 1 night on a luxury Alleppey houseboat.',
            status: 'Replied',
        },
        {
            id: 'inq-3',
            from: 'Amitabh Choudhary',
            email: 'amitabh.c@example.com',
            phone: '+91 98100 99887',
            subject: 'Corporate group tour to Rajasthan',
            channel: 'Email Direct',
            date: '25 Aug 2026',
            travelers: '18 Adults',
            budget: '₹8,00,000+',
            message: 'Organizing annual executive retreat in Jaipur and Udaipur. Need conference room facilities and gala dinner.',
            status: 'In Progress',
        },
        {
            id: 'inq-4',
            from: 'Divya Patel',
            email: 'divya.patel@example.com',
            phone: '+91 97250 11234',
            subject: 'Scuba diving & stay at Andaman',
            channel: 'Website Form',
            date: '24 Aug 2026',
            travelers: '2 Adults',
            budget: '₹90,000',
            message: 'Inquiring about Havelock Island scuba diving certification and 5 nights beach resort package.',
            status: 'Closed',
        },
    ],
    subscribers: [
        {
            id: 'sub-1',
            email: 'sarah.miller@gmail.com',
            source: 'Homepage Footer',
            date: '27 Aug 2026',
            city: 'Mumbai',
            status: 'Subscribed',
        },
        {
            id: 'sub-2',
            email: 'alex.traveler@outlook.com',
            source: 'Blog Newsletter Box',
            date: '26 Aug 2026',
            city: 'Bengaluru',
            status: 'Subscribed',
        },
        {
            id: 'sub-3',
            email: 'david.k@adventure.co',
            source: 'Homepage Footer',
            date: '24 Aug 2026',
            city: 'Delhi NCR',
            status: 'Subscribed',
        },
        {
            id: 'sub-4',
            email: 'elena.rossi@voyage.it',
            source: 'Destination Guide Popup',
            date: '20 Aug 2026',
            city: 'International',
            status: 'Subscribed',
        },
        {
            id: 'sub-5',
            email: 'vikram.travels@yahoo.com',
            source: 'Tour Deals Banner',
            date: '15 Aug 2026',
            city: 'Pune',
            status: 'Unsubscribed',
        },
    ],
};
